#! /usr/bin/env python3
# import conntact.spiral_search.main
# import conntact.spiral_search.main

import rospy

from conntact.corner_search_algorithm import CornerSearch

if __name__ == '__main__':
    rospy.init_node("demo_assembly_application_compliance")

    assembly_application = CornerSearch()

    assembly_application.main()

