#! /usr/bin/env python3

# Copyright 2021 Southwest Research Institute
# Licensed under the Apache License, Version 2.0

import rospy

from conntact.corner_search_algorithm import CornerSearch

if __name__ == '__main__':
    rospy.init_node("demo_assembly_application_compliance")

    assembly_application = CornerSearch()

    assembly_application.main()

