#! /usr/bin/env python3
# import peg_in_hole_demo.spiral_search.main
# import peg_in_hole_demo.spiral_search.main

import rospy

from peg_in_hole_demo.corner_search_algorithm import CornerSearch

if __name__ == '__main__':
    rospy.init_node("demo_assembly_application_compliance")

    assembly_application = CornerSearch()

    assembly_application.main()

