#! /usr/bin/env python3
# import peg_in_hole_demo.spiral_search.main
# import peg_in_hole_demo.spiral_search.main

import rospy

from peg_in_hole_demo.assembly_plotting import PlotAssemblyData

if __name__ == '__main__':
    rospy.init_node("Assembly_Plotter")

    plotter = PlotAssemblyData()

    plotter.main()

