#! /usr/bin/env python3
# import conntact.spiral_search.main
# import conntact.spiral_search.main

import rospy

from conntact.assembly_plotting import PlotAssemblyData

if __name__ == '__main__':
    rospy.init_node("Assembly_Plotter")

    plotter = PlotAssemblyData()

    plotter.main()

