#! /usr/bin/env python3

# Copyright 2021 Southwest Research Institute
# Licensed under the Apache License, Version 2.0

import rospy
import tf2_ros
import abc
from geometry_msgs.msg import WrenchStamped, Wrench, TransformStamped, PoseStamped, Pose, Point, Quaternion, Vector3, Transform
from std_msgs.msg import String

from conntact.spiral_search import SpiralSearch

if __name__ == '__main__':
    rospy.init_node("demo_assembly_application_compliance")

    assembly_application = SpiralSearch()

    # Need to pass in methods to do all the ROS stuff. Prototype definitions are below the main method.

    assembly_application.main()

