#! /usr/bin/env python3

# Copyright 2021 Southwest Research Institute
# Licensed under the Apache License, Version 2.0

import rospy
import tf2_ros
import abc
from geometry_msgs.msg import WrenchStamped, Wrench, TransformStamped, PoseStamped, Pose, Point, Quaternion, Vector3, Transform
from std_msgs.msg import String

from conntact.spiral_search import SpiralSearch
from conntact.ros_conntact_interface import ConntactROSInterface
from conntact.assembly_tools import AssemblyTools

if __name__ == '__main__':
    rospy.init_node("demo_assembly_application_compliance")

    refresh_rate    = 100
    interface       = ConntactROSInterface()
    conntext        = AssemblyTools(interface)

    # do pathing stuff then:
    assembly_application = SpiralSearch(refresh_rate, conntext, interface)
    assembly_application.main()

