#! /usr/bin/env python3

# Copyright 2021 Southwest Research Institute
# Licensed under the Apache License, Version 2.0

import rospy

from conntact.spiral_search import SpiralSearch

if __name__ == '__main__':
    rospy.init_node("demo_assembly_application_compliance")

    assembly_application = SpiralSearch()

    assembly_application.main()
