#! /usr/bin/env python3

# Copyright 2021 Southwest Research Institute
# Licensed under the Apache License, Version 2.0

import rospy

from conntact.static_force_test import StaticForceTest

if __name__ == '__main__':
    rospy.init_node("demo_assembly_application_compliance")

    assembly_application = StaticForceTest()

    assembly_application.main()
